### ISSUE TITLE
Close Encounters red ring does not appear

### ISSUE THREAD

**Issue by Favid** [Favid/LongWar2AbilitiesForWotC#1]
Close Encounters red ring does not appear. The particle effect for it is in the included in LW_Perk_CloseEncounters.upk file. Tried to just copy the implementation from LW2 but it doesn't seem to work. I suspect there is something new that has to be done for it to work with WotC, but I currently do not know what that is.

**Comment by TNychka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Close Encounters red ring does not appear.](https://trello.com/c/zGgDtzKP/8-close-encounters-red-ring-does-not-appear)

**Comment by Favid** [comment]
Wait until the next WotC Highlander update is released - it will provide an easy method for fixing this.

**Comment by Karnich** [comment]
@Favid this is already fixed right?

**Comment by Favid** [comment]
Yep, fixed by Highlander
